### ISSUE TITLE
Move website_docs back to website repo

### ISSUE THREAD

**Issue by chalin** [open-telemetry/opentelemetry-ruby#1395]
_Originally posted by @arielvalentin in https://github.com/open-telemetry/opentelemetry-ruby/issues/1394#issuecomment-1294225263_

> ... I am in favor of moving the docs! My one request is that @open-telemetry/ruby-approvers and @open-telemetry/ruby-contrib-approvers be granted collaborator access and added to `CODEOWNERS` to the ruby docs in repo so that we are able to approve PRs.
      
Contributes to https://github.com/open-telemetry/opentelemetry.io/issues/730. Tasks (in order):

- [x] Wait for #1394 to be merged
- [x] In website repo, perform the tasks detailed in https://github.com/open-telemetry/opentelemetry.io/issues/1942
- [ ] Delete `website_docs` from this repo - #1402

/cc @cartermp

**Comment by cartermp** [comment]
Everything's done on the website side of things! https://github.com/open-telemetry/opentelemetry.io/issues/1942
