### ISSUE TITLE
Errors Running Examples

### ISSUE THREAD

**Issue by arielvalentin** [open-telemetry/opentelemetry-ruby#652]
The Examples [`README`](https://github.com/open-telemetry/opentelemetry-ruby/tree/f68ba5e02394be7de6111f4f8f6583c945d8d3e6/examples/http#running-the-example) refer to a "Developer Setup" section in the main [`README`](https://github.com/open-telemetry/opentelemetry-ruby/blob/f68ba5e02394be7de6111f4f8f6583c945d8d3e6/README.md), which does not exist. 

Since I already have `docker` installed I was able to run one of the examples as described in the `README`: 

`docker-compose run ex-http`

However when entering the shell it printed an error:

```
Creating opentelemetry-ruby_ex-http_run ... done
Bundler could not find compatible versions for gem "opentelemetry-common":
  In Gemfile:
    opentelemetry-sdk was resolved to 0.15.0, which depends on
      opentelemetry-common (~> 0.15.0)
Could not find gem 'opentelemetry-common (~> 0.15.0)', which is required by gem 'opentelemetry-sdk', in any of the sources.
```

After updating the [Gemfile dependencies](https://github.com/open-telemetry/opentelemetry-ruby/pull/651) the examples would not print any output in some cases. Rather than updating all of the examples to use a `ConsoleSpanExporter`, the [team decided to allow configuration of the exporter using the `OTEL_TRACES_EXPORTERS` environment variable](https://cloud-native.slack.com/archives/C01NWKKMKMY/p1615396861054600?thread_ts=1615385309.053200&cid=C01NWKKMKMY).

In addition the that there are some examples fail due to errors:

- dalli
- delayed_job
- graph_ql
- mongo
- mysql-2
- sidekiq

The following do not have any example scripts or entires in `docker-compose`

- lmdb
- all
- http

Lastly these do not have an entires in `docker-compose`

- active_model_serializers
- http_client
- ruby_kafka

## Tasks

- [x] Add `console` option for `OTEL_TRACES_EXPORTERS` https://github.com/open-telemetry/opentelemetry-ruby/pull/650
- [x] Fix Dependency Errors https://github.com/open-telemetry/opentelemetry-ruby/pull/651
- [ ] Update README to include details about prerequisites to run the examples
- [ ] Fix errors in examples 
- [ ] Add `docker-compose` entries 
- [ ] Add examples for instrumentors

**Comment by fhwang** [comment]
Happy to take on getting the HTTP example cleaned up a bit, primarily just moving it off of docker-compose. It's useful for my work on #421.

**Comment by fhwang** [comment]
Care to take a look at #683?
