### ISSUE TITLE
Documentation Tracking Issue

### ISSUE THREAD

**Issue by arielvalentin** [open-telemetry/opentelemetry-ruby#775]
# Summary

_This issue is an action item outcome of the SIG meeting on 2021-05-25_

There are several requests for documentation to this project by both end users and contributors. As we are ready to work on tasks they may merit further exploration and discussion in sub-issues.

# Issues and Tasks

- [ ] [Documentation: Add design rationale to contributing guide](https://github.com/open-telemetry/opentelemetry-ruby/issues/105)
- [x] [Documentation: Add links or information on style to contributing](https://github.com/open-telemetry/opentelemetry-ruby/issues/106)
- [x] [Documentation: Add how to for bug reports](https://github.com/open-telemetry/opentelemetry-ruby/issues/107)
- [x] https://github.com/open-telemetry/opentelemetry-ruby/issues/872
- [x] https://github.com/open-telemetry/opentelemetry-ruby/pull/691
- [ ] [Span Processors are basically undocumented](https://github.com/open-telemetry/opentelemetry-ruby/issues/397)
- [ ] Create contribution guides for API, SDK, Instrumentation, and Exporters
- [ ] Create a sample Rails application that demonstrates steps required to configure the SDK
- [x] Stretch Goal: Contribute a microservice to [Hipster Shop](https://github.com/GoogleCloudPlatform/microservices-demo)

**Comment by fbogsany** [comment]
- [ ] [Add opentelemetry.io docs](https://github.com/open-telemetry/opentelemetry-ruby/pull/691)

**Comment by plantfansam** [comment]
Bug report template has [been added](https://github.com/open-telemetry/opentelemetry-ruby/pull/890), so I checked that off

**Comment by plantfansam** [comment]
Updated otel website docs here https://github.com/open-telemetry/opentelemetry.io/pull/1452. Probably would be good to automate this process in the `opentelemetry.io` repo 🤔

**Comment by ahayworth** [comment]
Our configuration docs could be better - see https://github.com/open-telemetry/opentelemetry-ruby-contrib/issues/88#issuecomment-1193145469
